import { generateObject } from "ai";
import { createTwoFilesPatch } from "diff";
import { desc, eq } from "drizzle-orm";
import type { Db } from "../db/client.js";
import { nowIso } from "../db/client.js";
import { qualifications, remediations, type Remediation } from "../db/schema.js";
import { fetchFileContent } from "../github/content.js";
import { createFixPr } from "../github/pr.js";
import { gatherContext } from "./context.js";
import { buildRemediatePrompt, REMEDIATE_SYSTEM } from "./prompts.js";
import { getModel, getModelName } from "./provider.js";
import { loadFindingBundle } from "./qualify.js";
import { remediationSchema } from "./schemas.js";

/**
 * Generate a fix for a (qualified) finding and open a PR on the target repo.
 * The LLM returns full replacement file contents; the display diff is
 * computed locally. PR creation failures keep the patch viewable.
 */
export async function remediateFinding(
  db: Db,
  findingId: number,
  options: { onProgress?: (msg: string) => void } = {},
): Promise<Remediation> {
  const progress = options.onProgress ?? (() => {});
  const { finding, repo, scan } = loadFindingBundle(db, findingId);

  const qualification = db
    .select()
    .from(qualifications)
    .where(eq(qualifications.findingId, findingId))
    .orderBy(desc(qualifications.id))
    .get();

  const row = db
    .insert(remediations)
    .values({
      findingId,
      qualificationId: qualification?.id ?? null,
      status: "generating",
      model: getModelName(),
      createdAt: nowIso(),
      updatedAt: nowIso(),
    })
    .returning()
    .get();

  const update = (values: Partial<typeof remediations.$inferInsert>) =>
    db
      .update(remediations)
      .set({ ...values, updatedAt: nowIso() })
      .where(eq(remediations.id, row.id))
      .returning()
      .get();

  try {
    progress("Gathering code context...");
    const context = await gatherContext(finding, repo, scan);

    progress("Generating fix with LLM...");
    const { object } = await generateObject({
      model: getModel(),
      schema: remediationSchema,
      system: REMEDIATE_SYSTEM,
      prompt: buildRemediatePrompt(
        finding,
        repo,
        qualification?.reasoning ?? null,
        context.text,
      ),
    });

    // Compute the display diff against the current file contents.
    const ref = scan?.commitSha ?? repo.defaultBranch ?? undefined;
    const patches: string[] = [];
    for (const file of object.files) {
      const original =
        (await fetchFileContent(repo.fullName, file.path, ref)) ?? "";
      patches.push(
        createTwoFilesPatch(
          `a/${file.path}`,
          `b/${file.path}`,
          original,
          file.new_content,
        ),
      );
    }
    const patchDiff = patches.join("\n");

    update({
      status: "patch_ready",
      explanation: object.explanation,
      patchDiff,
      filesChanged: JSON.stringify(object.files),
    });
    progress("Patch generated — opening pull request...");

    const branchName = `proofhouse-scan/fix-${findingId}-${finding.fingerprint.slice(0, 8)}`;
    const rotationNote = object.rotation_required
      ? "\n> ⚠️ **This finding involves a leaked credential.** Merging this PR does not un-leak it — rotate the credential immediately.\n"
      : "";
    const pr = await createFixPr({
      targetRepo: repo.fullName,
      branchName,
      files: object.files.map((f) => ({ path: f.path, newContent: f.new_content })),
      commitMessage: `fix(security): ${finding.ruleId} in ${finding.filePath}`,
      prTitle: `fix(security): ${finding.ruleId} in ${finding.filePath}`,
      prBody: `## Security fix generated by proofhouse-scan

**Finding:** \`${finding.ruleId}\` (${finding.scanner}, ${finding.severity}) in \`${finding.filePath}\`${finding.startLine ? ` line ${finding.startLine}` : ""}

**Scanner message:** ${finding.message}
${qualification?.reasoning ? `\n**Triage analysis:** ${qualification.reasoning}\n` : ""}
**Fix:** ${object.explanation}
${rotationNote}
---
*This pull request was generated automatically by [proofhouse-scan](https://github.com/${repo.owner}/proofhouse-scan). Review carefully before merging.*`,
      onProgress: progress,
    });

    return update({
      status: "pr_opened",
      branchName: pr.branchName,
      prUrl: pr.prUrl,
      prNumber: pr.prNumber,
      usedFork: pr.usedFork,
      forkFullName: pr.forkFullName,
    });
  } catch (err) {
    // Keep patch_ready state visible if the failure happened during PR creation.
    return update({ status: "failed", error: String(err) });
  }
}
